media:
  input: public/images
  output: /images

settings:
  title: Luigi Simiani — CMS
  description: Content management for luigisimiani.com
  locale: en

content:
  - name: settings
    label: Site Settings
    path: content/settings.json
    type: file
    fields:
      - name: heroTitle
        label: Hero Title
        type: string
      - name: featuredTitle
        label: Featured Section Title
        type: string

  - name: bio
    label: Bio
    path: content/bio.json
    type: file
    fields:
      - name: paragraphs
        label: Paragraphs
        type: object[]
        fields:
          - name: id
            label: ID
            type: string
          - name: value
            label: Text
            type: rich-text

  - name: contact
    label: Contact Info
    path: content/contact.json
    type: file
    fields:
      - name: email
        label: Email
        type: string
      - name: location
        label: Location
        type: string
      - name: instagram
        label: Instagram Handle
        type: string
      - name: linkedin
        label: LinkedIn URL
        type: string

  - name: featured
    label: Featured Work
    path: content/featured.json
    type: file
    fields:
      - name: galleries
        label: Featured Gallery Slugs
        type: string[]

  - name: quotes
    label: Quotes
    path: content/quotes.json
    type: file
    fields:
      - name: quotes
        label: Quotes
        type: object[]
        fields:
          - name: text
            label: Quote Text
            type: string
          - name: author
            label: Author
            type: string

  - name: film-strip
    label: Film Strip
    path: content/film-strip.json
    type: file
    fields:
      - name: images
        label: Film Strip Images
        type: object[]
        fields:
          - name: url
            label: Image URL
            type: image
          - name: orientation
            label: Orientation
            type: string
          - name: aspectRatio
            label: Aspect Ratio
            type: number

  - name: gallery
    label: Gallery Projects
    path: content/gallery
    type: collection
    filename: "{fields.id}.json"
    view:
      fields: [title, featured]
      primary: title
    fields:
      - name: id
        label: Slug / ID
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: subTitle
        label: Subtitle
        type: string
      - name: featured
        label: Featured
        type: boolean
      - name: coverPhoto
        label: Cover Photo
        type: image
      - name: imageUrls
        label: Gallery Images
        type: image[]
      - name: imageAspectRatios
        label: Image Aspect Ratios
        type: number[]
